[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.36"

[[constraint]]
  name = "github.com/google/go-github"
  version = "25.0.2"

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "v5.12.1"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/robfig/cron.v3"

[prune]
  go-tests = true
  unused-packages = true
