[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.36"

[[constraint]]
  name = "github.com/google/go-github"
  version = "3.0.0"

[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
  branch = "v3"
  name = "gopkg.in/robfig/cron.v3"
