[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.36"

[[constraint]]
  name = "github.com/google/go-github"
  version = "25.0.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  packages = [
    "mlog",
    "model",
    "services/timezones",
    "utils/fileutils",
    "utils/jsonutils",
    "utils/markdown",
  ]
  version = "v5.11.0"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/robfig/cron.v3"
