version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12-node

    working_directory: /go/src/github.com/mattermost/mattermost-mattermod
    steps:
      - checkout
      - run: make check-style

  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/mattermost/mattermost-mattermod
    steps:
      - checkout
      - run: go build .

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - build:
          requires:
            - lint
